name: centerline_width
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12  # minimum support 3.9
  - geopy
  - haversine
  - networkx
  - numpy
  - pandas
  - pykml
  - pyproj
  - pytest
  - scipy
  - shapely
  - pip
  - pip:
    - matplotlib # avoid warning "QApplication: invalid style override passed, ignoring it."
