name: centerline_width
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14  # minimum support 3.10, maximum support 3.13
  - geopy
  - haversine
  - networkx
  - numpy
  - pandas
  - pyarrow
  - pykml
  - pyproj
  - scipy
  - shapely
  - pytest      # dev: testing
  - pytest-cov  # dev: codecov reports
  - pre-commit  # dev: pre-commit hooks
  - pip
  - pip:
    - matplotlib # avoid warning "QApplication: invalid style override passed, ignoring it."
